version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: golang-api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgre
    container_name: golang-api-db
    restart: always
    shm_size: 500mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
