CREATE TABLE PRODUCT (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(50) NOT NULL,
        PRICE NUMERIC(10,2) NOT NULL DEFAULT 0
    );

INSERT INTO PRODUCT(NAME, PRICE) VALUES('HAMBURGUER', 25);
INSERT INTO PRODUCT(NAME, PRICE) VALUES('ORANGE JUICE', 15);
INSERT INTO PRODUCT(NAME, PRICE) VALUES('SODA', 5);
INSERT INTO PRODUCT(NAME, PRICE) VALUES('PIZZA', 35);